ALTER TABLE Alunos ADD COLUMN data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP;
-- //admin123
ALTER TABLE Alunos ADD COLUMN senha_padrao VARCHAR(255) DEFAULT '$2b$10$K7L/8Y1t85iCFyOeDrHWpuHEHPmBcVBpYuvsDeNp2CGZXwsSAhHWW';
ALTER TABLE Alunos ADD COLUMN primeiro_acesso BOOLEAN DEFAULT TRUE;