-- Criar tabela de planos
CREATE TABLE Planos (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  treinos_por_semana INT(11) NOT NULL,
  valor DECIMAL(10,2) DEFAULT NULL,
  ativo TINYINT(1) DEFAULT 1,
  data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;